--- 
addons: 
  apt: 
    packages: 
      - cmake
compiler: 
  - gcc
  - clang
language: cpp
os: 
  - linux
  - osx
script: 
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles" -DBUILD_HEADLESS="ON"
  - make -j4


